// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi_qkqBpRxdecT8mz4O0pd747z9uO1yqg',
    appId: '1:579260236321:web:1cb2178be7a1531fda5960',
    messagingSenderId: '579260236321',
    projectId: 'qrcodeinventory-get',
    authDomain: 'qrcodeinventory-get.firebaseapp.com',
    storageBucket: 'qrcodeinventory-get.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxLKHQvrGlRcpIwuYh4uXQkFbMdptremA',
    appId: '1:579260236321:android:9c7b37204579f2e1da5960',
    messagingSenderId: '579260236321',
    projectId: 'qrcodeinventory-get',
    storageBucket: 'qrcodeinventory-get.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVuz9E7W2h8uUrTdYsKSA96Ewj0x2i97Y',
    appId: '1:579260236321:ios:0dea5fe1c9a529eeda5960',
    messagingSenderId: '579260236321',
    projectId: 'qrcodeinventory-get',
    storageBucket: 'qrcodeinventory-get.firebasestorage.app',
    iosBundleId: 'com.nekoproject.inventoryQrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVuz9E7W2h8uUrTdYsKSA96Ewj0x2i97Y',
    appId: '1:579260236321:ios:0dea5fe1c9a529eeda5960',
    messagingSenderId: '579260236321',
    projectId: 'qrcodeinventory-get',
    storageBucket: 'qrcodeinventory-get.firebasestorage.app',
    iosBundleId: 'com.nekoproject.inventoryQrCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi_qkqBpRxdecT8mz4O0pd747z9uO1yqg',
    appId: '1:579260236321:web:611e3c9f73fd780eda5960',
    messagingSenderId: '579260236321',
    projectId: 'qrcodeinventory-get',
    authDomain: 'qrcodeinventory-get.firebaseapp.com',
    storageBucket: 'qrcodeinventory-get.firebasestorage.app',
  );

}